name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build
        run: go build ./...

      - name: Run tests
        run: go test ./...

      - name: Install project
        run: go install ./...

      - name: Run application
        run: $GOPATH/bin/your-application-name
